# nome da aplica��o (logs/actuator)
spring.application.name=bankSecure
# H2 em mem�ria, mant�m DB ativo
spring.datasource.url=jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# driver JDBC do H2
spring.datasource.driver-class-name=org.h2.Driver
# usu�rio padr�o do H2
spring.datasource.username=sa
# senha (vazia por padr�o)
spring.datasource.password=
# ativa console web do H2
spring.h2.console.enabled=true
# caminho do console H2
spring.h2.console.path=/h2-console
# gerencia schema (update preserva dados)
spring.jpa.hibernate.ddl-auto=update
# exibe SQL no log
spring.jpa.show-sql=true
# formata SQL logado
spring.jpa.properties.hibernate.format_sql=true
# dialeto do Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect